folders:
  - folder_path: "odin"
    description: "odin service jobs"
jobs:
  - job_path: "odin/build_job"
    jenkinsfile_git_repo: "https://github.com/prashant-ee/odin.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
